# Generated by Django 3.2.19 on 2023-06-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0003_auto_20230622_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='business_event',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='business_status',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='business_event',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='business_status',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
