# Generated by Django 3.2.19 on 2023-06-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks_management', '0003_historicaltaskexecutor_taskexecutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='business_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='business_status',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='entity_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='entity_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='executor_action_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='business_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='business_status',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='entity_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='entity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor_action_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks_management.taskgroup'),
        ),
    ]
