# Generated by Django 3.2.19 on 2023-06-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0005_add_task_rigts_for_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltask',
            old_name='content_type',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='content_type',
            new_name='entity_type',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='complete_action',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='data',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete_action',
        ),
        migrations.RemoveField(
            model_name='task',
            name='data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='object_id',
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='entity_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='executor_action_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='entity_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='executor_action_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='business_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='business_status',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='business_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='business_status',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=255),
        ),
    ]
