# Generated by Django 3.2.21 on 2023-09-29 14:35

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_mutationlog_json_ext'),
        ('tasks_management', '0006_add_search_users_to_task_triage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to='core.mutationlog')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='tasks_management.task')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
