# Generated by Django 3.2.21 on 2024-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0007_taskmutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='business_data_serializer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='business_data_serializer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
